### ISSUE TITLE
Align React peer dependencies with graphiql

### ISSUE THREAD

**Issue by oliversalzburg** [productfy/graphiql-tree#24]
The problematic dependencies that I see are:
- react: `^17.0.1`
- react-dom: `^17.0.1`

GraphiQL defines these dependencies as:
- react: `^16.8.0`
- react-dom: `^16.8.0`

As I need `graphiql` and `graphiql-tree` in my dependencies, it's impossible to include both without creating a conflict in the react dependencies.

I would suggest declaring the range as `^16.8.0 || ^17.0.1` until graphiql updates their dependencies.

**Comment by baohouse** [comment]
Fixed in [v0.7.0 release](https://github.com/productfy/graphiql-tree/releases/tag/v0.7.0)
